services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
